Feature/more unit tests
exomath/core pull request #4
Opened 2021-06-30 04:23 UTC by uzairsyedahmed

Add unit tests for : 

isBoolean
isInfinity
isInteger
isIntegerArray
isNaN
isNull

2021-07-08 19:14 UTC, jakemckown requested changes
These unit tests look good man. Check out the line comments for `is.test.ts`.

2021-07-08 19:14 UTC, jakemckown commented on src/is.test.ts
> +});
Let's get a bit more thorough and use multiple `expect`s to test different values. Something like:

```suggestion
  it('Should return true when "value" is type boolean', () => {
    expect(isBoolean(true)).to.equal(true);
    expect(isBoolean(false)).to.equal(true);
  });

  it('Should return false when "value" is not type boolean', () => {
    expect(isBoolean('This is a string')).to.equal(false);
    expect(isBoolean(100)).to.equal(false);
    expect(isBoolean([])).to.equal(false);
    expect(isBoolean({})).to.equal(false);
  });
});
```

Same with all the others.

2021-07-08 19:14 UTC, jakemckown commented on src/is.test.ts
> +describe('isInteger(value)', () => {
Be careful, when copying and pasting code, to check each line.

```suggestion
describe('isIntegerArray(value)', () => {
```

2021-07-08 19:14 UTC, jakemckown commented on src/is.test.ts
> +});
This can either be combined into a single `it` with multiple `expect`s, or the "should" message for each one can be changed to what specifically is being tested (preferred):

```suggestion
  it('Should return false when "value" is not type number[]', () => {
    expect(isIntegerArray([1, '2', true])).to.equal(false);
  });

  it('Should return false when "value" is type number[] but not every array entry is an integer', () => {
    expect(isIntegerArray([1, 2.2, 3.3])).to.equal(false);
  });
});
```

2021-07-08 19:34 UTC, uzairsyedahmed commented on src/is.test.ts
> +});
Should I keep it to a single `it` to keep it inline with the first comment where we combined the falses into one it 

```
    expect(isBoolean('This is a string')).to.equal(false);
    expect(isBoolean(100)).to.equal(false);
    expect(isBoolean([])).to.equal(false);
    expect(isBoolean({})).to.equal(false);
 ```

2021-07-08 19:47 UTC, jakemckown commented on src/is.test.ts
> +});
In this case, I think they might be better as separate tests. The reason is that the message for the first one is `Should return false when "value" is not type number[]`, so you could add multiple `expect`s that test other non-`number[]` values like `100` and `{}`. But the next test is for the case where the value is a `number[]`, but now we're looking at the specific type of number for each element.

2021-07-08 19:50 UTC, uzairsyedahmed commented on src/is.test.ts
> +});
Agreed. That makes sense. In this case, we are trying to segregate the falses into a) when its not a number[] and b) to when its a number[] but not the type of number as elements that we are expecting.

2021-07-08 19:52 UTC, jakemckown commented on src/is.test.ts
> +});
If we go with a two-`it` approach for every function tested, we would end up with messages like `Should return true when "value" is type number[] and each element is an integer` for one and `Should return false when "value" is not type number[] or when "value" is type number[] but each element is not an integer`, which is probably too long.

2021-07-11 20:15 UTC, uzairsyedahmed commented
@jakemckown , I pushed a commit on the changes I made to both is.test.ts and is.ts. Take a look!

2021-07-20 17:28 UTC, jakemckown commented on src/is.test.ts
> +  });
Let's add checks for the various ways that you can get the value Infinity:

```suggestion
  it('Should return true when "value" is Infinity', () => {
    expect(isInfinity(Infinity)).to.equal(true);
    expect(isInfinity(-Infinity)).to.equal(true);
    expect(isInfinity(Number.POSITIVE_INFINITY)).to.equal(true);
    expect(isInfinity(Number.NEGATIVE_INFINITY)).to.equal(true);
    expect(isInfinity(Number.MAX_VALUE * 1.000000000000001)).to.equal(true);
  });
```

2021-07-20 17:30 UTC, jakemckown commented on src/is.test.ts
> +    expect(isInfinity('This is a string')).to.equal(false);
```suggestion
    expect(isInfinity(Number.MAX_VALUE)).to.equal(false);
    expect(isInfinity('This is a string')).to.equal(false);
```

2021-07-20 17:32 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return true when "value" is an Integer', () => {
Let's lowercase "integer" since it's not an actual type or class:

```suggestion
  it('Should return true when "value" is an integer', () => {
```

2021-07-20 17:33 UTC, jakemckown commented on src/is.test.ts
> +    expect(isInteger(100.00)).to.equal(true);
Similar to Infinity, let's check for other ways to get integers:

```suggestion
    expect(isInteger(100.00)).to.equal(true);
    expect(isInteger(Number.MAX_SAFE_INTEGER)).to.equal(true);
    expect(isInteger(Number.MIN_SAFE_INTEGER)).to.equal(true);
```

2021-07-20 17:33 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return false when "value" is not an Integer', () => {
```suggestion
  it('Should return false when "value" is not an integer', () => {
```

2021-07-20 17:37 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return true when "value" is type number[] and each array entry is an integer', () => {
```suggestion
  it('Should return true when "value" is type number[] and each element is an integer', () => {
```

2021-07-20 17:38 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return false when "value" is type number[] but not every array entry is an integer', () => {
```suggestion
  it('Should return false when "value" is type number[] but not every element is an integer', () => {
```

2021-07-20 17:42 UTC, jakemckown commented on src/is.test.ts
> +  });
Check other ways to get NaN:

```suggestion
  it('Should return true when "value" is NaN', () => {
    expect(isNaN(NaN)).to.equal(true);
    expect(parseInt('No number')).to.equal(true);
    expect(parseFloat('No number')).to.equal(true);
  });
```

2021-07-20 17:46 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return true when "value" is type any{}', () => {
any{} is not a valid type:

```suggestion
  it('Should return true when "value" is type object', () => {
```

2021-07-20 17:46 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return false when "value" is not type any{}', () => {
```suggestion
  it('Should return false when "value" is not type object', () => {
```

2021-07-20 17:48 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return true when "value" is a Number', () => {
Let's keep the descriptions consistent and use TypeScript types:

```suggestion
  it('Should return true when "value" is type number', () => {
```

2021-07-20 17:51 UTC, jakemckown commented on src/is.test.ts
> +    expect(isNumber(0)).to.equal(true);
Add more ways to get a number:

```suggestion
    expect(isNumber(0)).to.equal(true);
    expect(isNumber(Infinity)).to.equal(true);
    expect(isNumber(NaN)).to.equal(true);
    expect(isNumber(Number.MAX_VALUE)).to.equal(true);
    expect(isNumber(parseFloat('1.1'))).to.equal(true);
    expect(isNumber(parseInt('1'))).to.equal(true);
```

2021-07-20 17:51 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return false when "value" is not a Number', () => {
```suggestion
  it('Should return false when "value" is not type number', () => {
```

2021-07-20 17:53 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return true when "value" is a String', () => {
```suggestion
  it('Should return true when "value" is type string', () => {
```

2021-07-20 17:53 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return false when "value" is not a String', () => {
```suggestion
  it('Should return false when "value" is not type string', () => {
```

2021-07-20 17:54 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return true when "value" is type String[]', () => {
```suggestion
  it('Should return true when "value" is type string[]', () => {
```

2021-07-20 17:54 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return false when "value" is not type String[]', () => {
```suggestion
  it('Should return false when "value" is not type string[]', () => {
```

2021-07-20 17:55 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return true when "value" is an Int8Array', () => {
Keep description consistent:

```suggestion
  it('Should return true when "value" is type Int8Array', () => {
```

2021-07-20 17:56 UTC, jakemckown commented on src/is.test.ts
> +  it('Should return false when "value" is not an Int8Array', () => {
```suggestion
  it('Should return false when "value" is not type Int8Array', () => {
```

2021-07-20 17:57 UTC, jakemckown commented on src/is.test.ts
> +    expect(isInt8Array(new Float64Array())).to.equal(false);
Add a Uint8Array for good measure:

```suggestion
    expect(isInt8Array(new Float64Array())).to.equal(false);
    expect(isInt8Array(new Uint8Array())).to.equal(false);
```

2021-07-20 17:58 UTC, jakemckown requested changes
Looking much better with the added `expect`s! Check out my comments for some small changes/additions.

2021-07-25 15:42 UTC, uzairsyedahmed commented on src/is.test.ts
> +  });
Will do. Will also check for mathematical Infinity ( number /0).

2021-07-25 15:44 UTC, uzairsyedahmed commented on src/is.test.ts
> +    expect(isInteger(100.00)).to.equal(true);
Okay. Do you want me to check other integers (like different numbers with varying magnitudes) or other inbuilt constants (like MAX_SAFE_INTEGER)?

2021-07-25 17:32 UTC, jakemckown commented on src/is.test.ts
> +    expect(isInteger(100.00)).to.equal(true);
No I think this is good.

2021-07-26 05:12 UTC, uzairsyedahmed commented on src/is.test.ts
> +    expect(isInteger(100.00)).to.equal(true);
okay. Then I will commit the suggestions, take a look and send the pull request for it to be merged!

2021-07-26 22:39 UTC, uzairsyedahmed commented on src/is.test.ts
> +  });
should I try other ways of NaN? A google search shows that 1*undefined also results in NaN. I am seeing some examples of parseInt like ```parseInt('Joker', 10); // => NaN``` . I was thinking to do that too.

2021-07-26 22:40 UTC, uzairsyedahmed commented on src/is.test.ts
> +  });
I guess 'No number' is a String and it should cover string as an input that is parsed and becomes NaN

2021-07-29 03:33 UTC, jakemckown commented on src/is.test.ts
> +  });
Right, that was my intention behind parsing `'No number'`. Beyond that, we would just be testing the parse functions :smile:

2021-08-18 01:08 UTC, jakemckown approved these changes
Looks great!

2021-11-02 05:14 UTC, merged